name: HAIKO-MDX 
services:
  - name: HAIKO-MDX 
    type: web
    ports:
      - 5000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin


      
